// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://eqcigfmrxvylmckwlbhz.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImVxY2lnZm1yeHZ5bG1ja3dsYmh6Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDk5ODY3NDUsImV4cCI6MjA2NTU2Mjc0NX0.LnmqqdMTWkqrbCDRhS4YZ-Mk1viF9oVJr5WxMEAWbHc";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);